### ISSUE TITLE
Cargo.lock in repo

### ISSUE THREAD

**Issue by goertzenator** [sdwolf/rustfromerl#1]
Cargo.lock typically should not be committed to a repo.

**Comment by sdwolf** [comment]
I've read about the purpose of `Cargo.lock` [here](http://doc.crates.io/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) and I believe it should stay in this case since this library is actually the end product (not intended to be used outside of the project). Also i would pretty much like 100% reproducible builds for it.

**Comment by goertzenator** [comment]
Whoops, you are right.  I've been in library land for too long.
